kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-k8s-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: "rendani24/website:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8ssvc
  namespace: default
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort
